version: "3.3"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: cny_sh_mongodb
    env_file: 
      - .env
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
