version: "3.3"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: cny_sh_mongodb
    env_file: 
      - .env
    volumes:
      - ./docker/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  nextjs:
    container_name: cny_sh_nextjs
    build:
      context: ./
      target: runner
    volumes:
      - ./docker/next:/next
    command: npm run start:next
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    links: 
      - mongodb