version: "3.3"
services:
  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: DwQe97XrzqUe36zTMVBbHN2pug6zN2ENd9p5bu4PZFtZ7ngFpVc6XWMrxzjJa4dV
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
