name: Deploy Docker Image

on:
  push:
    branches:
      - production

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Build and push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: cny_sh
        tags: latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
